import type { Config } from 'tailwindcss';

/**
 * Nvite design tokens — ported 1:1 from the approved landing design.
 * Class names from the design (bg-surface, text-on-surface, text-display,
 * font-headline-sm, px-gutter, ...) work directly with this config.
 */
const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './lib/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#ffdad9',
        outline: '#936e6d',
        'surface-tint': '#bf002e',
        'tertiary-container': '#e70052',
        background: '#fcf8fc',
        'secondary-fixed': '#ffdcc6',
        'surface-container': '#f0edf1',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e4e1e6',
        'secondary-fixed-dim': '#ffb785',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-low': '#f6f2f7',
        'on-surface-variant': '#5e3f3e',
        'surface-bright': '#fcf8fc',
        'on-primary-container': '#fffbff',
        error: '#ba1a1a',
        'surface-dim': '#dcd9dd',
        'tertiary-fixed-dim': '#ffb2ba',
        'on-tertiary-fixed': '#400010',
        'tertiary-fixed': '#ffd9dc',
        'on-secondary-fixed': '#301400',
        'inverse-on-surface': '#f3f0f4',
        'inverse-primary': '#ffb3b3',
        'on-secondary-container': '#6c3400',
        'secondary-container': '#fc984b',
        primary: '#ba002c',
        secondary: '#954a00',
        'on-primary-fixed': '#400009',
        'primary-fixed-dim': '#ffb3b3',
        tertiary: '#b90040',
        'on-error': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-primary': '#ffffff',
        'on-background': '#1b1b1e',
        'on-primary-fixed-variant': '#920021',
        'on-error-container': '#93000a',
        'primary-container': '#e9003a',
        'on-secondary-fixed-variant': '#713700',
        'on-tertiary-fixed-variant': '#910030',
        'on-secondary': '#ffffff',
        'surface-container-high': '#eae7eb',
        'inverse-surface': '#303033',
        'outline-variant': '#e8bcbb',
        'surface-container-highest': '#e4e1e6',
        surface: '#fcf8fc',
        'on-surface': '#1b1b1e',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'display-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        title: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'mono-metric': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-mobile': [
          '36px',
          { lineHeight: '42px', letterSpacing: '-0.025em', fontWeight: '600' },
        ],
        'headline-lg': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.025em', fontWeight: '600' },
        ],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-md': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'headline-sm': [
          '20px',
          { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' },
        ],
        title: ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'mono-metric': [
          '24px',
          { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '500' },
        ],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
      },
    },
  },
  plugins: [],
};

export default config;
